name: lurniva
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0  # move this from dev to main dependencies
  image_picker: ^1.0.7
  lottie: ^3.0.0
  shimmer: ^3.0.0
  table_calendar: ^3.0.9 
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  animations: ^2.0.8
  fl_chart: ^0.66.0
  file_picker: ^8.1.3
  http: ^1.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  table_calendar: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_dark.png
    - assets/images/student_img.jpeg
    - assets/images/Farman.jpg
    - assets/images/urdu_book.jpeg
    - assets/images/english_book.jpeg
    - assets/images/is_book.jpeg
    - assets/images/pakstudy_book.jpeg
    - assets/images/Science.jpeg
    - assets/images/physics_book.jpeg
    - assets/images/Chymistry_book.jpeg
    - assets/images/Maths_book.jpeg
    - assets/images/hero_bg_pattern.jpeg

    
